export { Column, type ColumnProps } from "./components/Column.js";
export { Row } from "./components/Row.js";
export { Text, type TextProps } from "./components/Text.js";
export { Heading, type HeadingProps } from "./components/Heading.js";
export { Button, type ButtonProps } from "./components/Button.js";
export { Input, type InputProps } from "./components/Input.js";
export { Surface, type SurfaceProps } from "./components/Surface.js";
export { Card, type CardProps } from "./components/Card.js";
export { Link, type LinkProps } from "./components/Link.js";
export { Spacer, SpacerBox, type SpacerProps } from "./components/Spacer.js";
export { Visibility } from "./components/Visibility.js";
export { Conditional } from "./components/Conditional.js";
export { ForEach } from "./components/ForEach.js";
export { render } from "./components/render.js";
import { Column } from "./components/Column.js";
import { Row } from "./components/Row.js";
import { Text } from "./components/Text.js";
import { Heading } from "./components/Heading.js";
import { Button } from "./components/Button.js";
import { Input } from "./components/Input.js";
import { Surface } from "./components/Surface.js";
import { Card } from "./components/Card.js";
import { Link } from "./components/Link.js";
import { Spacer, SpacerBox } from "./components/Spacer.js";
import { Visibility } from "./components/Visibility.js";
import { Conditional } from "./components/Conditional.js";
import { ForEach } from "./components/ForEach.js";
import { render } from "./components/render.js";
export declare const UI: {
    Column: typeof Column;
    Row: typeof Row;
    Text: typeof Text;
    Heading: typeof Heading;
    Button: typeof Button;
    Input: typeof Input;
    Surface: typeof Surface;
    Card: typeof Card;
    Link: typeof Link;
    Spacer: typeof Spacer;
    SpacerBox: typeof SpacerBox;
    Visibility: typeof Visibility;
    Conditional: typeof Conditional;
    ForEach: typeof ForEach;
    render: typeof render;
};
