import { TSX5Node } from "../global";
export declare function Column(children: () => TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Row(children: () => TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Text(content: string, props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Title(text: string, level?: number, props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Button(label: string, props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Input(props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Label(text: string, htmlFor: string, props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Textarea(props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Select(options: Array<string | {
    label: string;
    value: string;
    group?: string;
    disabled?: boolean;
}>, props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Form(children: () => TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function FormGroup(label: string, input: TSX5Node, id?: string): TSX5Node;
export declare function Spacer(height?: string, props?: Record<string, any>): TSX5Node;
export declare function Image(src: string, alt?: string, props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Surface(children: () => TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Card(children: () => TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Table<T = any>(headers: string[], rows: T[], renderRow: (row: T, index: number) => TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Ul(items: TSX5Node[], props?: Record<string, any>, style?: Partial<CSSStyleDeclaration>): TSX5Node;
export declare function Visibility(visible: boolean, child: () => TSX5Node): TSX5Node;
export declare function Conditional(cond: boolean, whenTrue: () => TSX5Node, whenFalse?: () => TSX5Node): TSX5Node;
export declare function ForEach<T>(items: T[], render: (item: T, index: number) => TSX5Node): TSX5Node[];
export declare function InjectJSX(component: () => TSX5Node): TSX5Node;
export declare function render(ui: () => TSX5Node): TSX5Node;
export declare const Compose: {
    Column: typeof Column;
    Row: typeof Row;
    Text: typeof Text;
    Title: typeof Title;
    Button: typeof Button;
    Input: typeof Input;
    Label: typeof Label;
    Textarea: typeof Textarea;
    Select: typeof Select;
    Form: typeof Form;
    FormGroup: typeof FormGroup;
    Spacer: typeof Spacer;
    Image: typeof Image;
    Surface: typeof Surface;
    Card: typeof Card;
    Table: typeof Table;
    Ul: typeof Ul;
    Visibility: typeof Visibility;
    Conditional: typeof Conditional;
    ForEach: typeof ForEach;
    InjectJSX: typeof InjectJSX;
    render: typeof render;
};
export declare const Box: typeof Surface;
